import { Injectable } from '@nestjs/common';

export interface SecurityEvent {
  id: string;
  type: string;
  severity: 'low' | 'medium' | 'high' | 'critical';
  description: string;
  timestamp: number;
  ipAddress: string;
}

@Injectable()
export class SecurityService {
  private readonly events: SecurityEvent[] = [];

  constructor() {
    // Seed mock data
    this.events.push({
      id: 'sec_1',
      type: 'failed_login',
      severity: 'medium',
      description: '5 failed login attempts for admin@org.com',
      timestamp: Date.now() - 3600000,
      ipAddress: '192.168.1.100'
    });
    this.events.push({
      id: 'sec_2',
      type: 'api_key_created',
      severity: 'low',
      description: 'New Live API Key generated by user_123',
      timestamp: Date.now() - 7200000,
      ipAddress: '10.0.0.5'
    });
  }

  getRecentEvents(): SecurityEvent[] {
    return this.events.sort((a, b) => b.timestamp - a.timestamp);
  }

  getSecurityPosture() {
    return {
      status: 'Secure',
      activeThreats: 0,
      failedLogins24h: 12,
      activeApiKeys: 4
    };
  }
}
